from main import efficiency
from main import kinetic
from main import gpe
from main import Length_Unit_Converter
from main import Temprature_Unit_Converter
from main import Get_Wavelength
from main import Get_Wave_Speed
from main import Get_Frequency
from main import Get_KWh
